In [1]:
import numpy as np
import pandas as pd
import scipy
import sklearn
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [2]:
A= np.array([[1,2,3], [4,5,6]])

In [3]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
A.T.T

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
B=np.array([[7,8,9], [10,11,12]])

In [6]:
np.dot(A,B.T)

array([[ 50,  68],
       [122, 167]])

In [7]:
C=A**2

In [8]:
C

array([[ 1,  4,  9],
       [16, 25, 36]])

In [9]:
D= A-1

In [10]:
D

array([[0, 1, 2],
       [3, 4, 5]])

In [11]:
C2=np.array([[1,2,3], [1,2,3], [3,4,5]])

In [12]:
C2

array([[1, 2, 3],
       [1, 2, 3],
       [3, 4, 5]])

In [13]:
C2.diagonal()

array([1, 2, 5])

In [14]:
A=np.matrix(A)

In [15]:
type(A)

numpy.matrix

In [16]:
B=np.matrix(B)

In [17]:
C=np.matrix(C)

In [18]:
A

matrix([[1, 2, 3],
        [4, 5, 6]])

In [19]:
A.nonzero()

(array([0, 0, 0, 1, 1, 1]), array([0, 1, 2, 0, 1, 2]))

In [20]:
A-B

matrix([[-6, -6, -6],
        [-6, -6, -6]])

In [21]:
A+B

matrix([[ 8, 10, 12],
        [14, 16, 18]])

In [22]:
A.dot(B.T)

matrix([[ 50,  68],
        [122, 167]])

In [23]:
A

matrix([[1, 2, 3],
        [4, 5, 6]])

In [24]:
print(A.sum(), A.mean(), A.std(), A.var())

21 3.5 1.707825127659933 2.9166666666666665


In [25]:
A_df=pd.DataFrame(A)

In [26]:
type(A_df)

pandas.core.frame.DataFrame

# SQL

In [27]:
## Postgre SQL, SQLite

Relational DB Download sqlite studio (GUI) https://sqlitestudio.pl/index.rvt

In [28]:
# select * from procedure;

# select  specialty, count(id) as physician_count 
# from physician
# group by specialty
# order by 2 desc 
# limit 10 ;


# select  specialty, count(distinct procedure_code)  
# from  physician a 
# join procedure b on a.id=b.physician_id
# group by specialty ;